services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: secure_sight
    ports:
      - 5432:5432
    volumes:
      - pd_data:/var/lib/postgresql/data
    depends_on:
      - adminer

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pd_data: